services:
  redis:
    image: redis:8-alpine
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - 'redis:/data'

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - 'mongo:/data/db'

volumes:
  redis:
    driver: local
  mongo:
    driver: local
